# Generated by Django 4.0.2 on 2022-02-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hi', max_length=20)),
                ('price', models.IntegerField(default=1)),
            ],
        ),
    ]
