# Generated by Django 4.0.2 on 2022-02-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no value', max_length=20)),
                ('address', models.CharField(default='no value', max_length=20)),
                ('mobileNum', models.IntegerField(default=1)),
                ('dob', models.IntegerField(default=1)),
                ('lockerNum', models.IntegerField(default=1)),
                ('reg_no', models.IntegerField(default=1)),
                ('membership_no', models.IntegerField(default=1)),
                ('package', models.CharField(default='no value', max_length=20)),
                ('startDate', models.IntegerField(default=1)),
                ('period', models.IntegerField(default=1)),
                ('endDate', models.IntegerField(default=1)),
            ],
        ),
    ]
