# Generated by Django 4.0.2 on 2022-02-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='no value', max_length=20)),
                ('password', models.CharField(default='no value', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ClassName',
        ),
    ]
