# Generated by Django 4.0.2 on 2022-03-20 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profiledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.CharField(max_length=20)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('neck', models.IntegerField(default=0)),
                ('shoulder', models.IntegerField(default=0)),
                ('chest', models.IntegerField(default=0)),
                ('upperArm', models.IntegerField(default=0)),
                ('forearm', models.IntegerField(default=0)),
                ('upperAbdomen', models.IntegerField(default=0)),
                ('lowerAbdomen', models.IntegerField(default=0)),
                ('waist', models.IntegerField(default=0)),
                ('hips', models.IntegerField(default=0)),
                ('thighs', models.IntegerField(default=0)),
                ('calf', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('name', models.CharField(default='no value', max_length=30)),
                ('bio', models.CharField(default='no value', max_length=20)),
                ('gender', models.CharField(default='no value', max_length=20)),
                ('age', models.IntegerField(default=1)),
                ('address', models.CharField(default='no value', max_length=100)),
                ('mobileNum', models.IntegerField(default=1)),
                ('dob', models.IntegerField(default=1)),
                ('lockerNum', models.IntegerField(default=1)),
                ('reg_no', models.IntegerField(default=1)),
                ('membership_no', models.IntegerField(default=1)),
                ('package', models.CharField(default='no value', max_length=20)),
                ('startDate', models.IntegerField(default=1)),
                ('period', models.IntegerField(default=1)),
                ('endDate', models.IntegerField(default=1)),
                ('isApproved', models.BooleanField(default=False)),
                ('m_uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='muid', serialize=False, to='core.authuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='uid',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='authuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProfileData',
        ),
        migrations.AddField(
            model_name='gymtrack',
            name='g_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guid', to='core.authuser'),
        ),
    ]
