# Generated by Django 4.0.2 on 2022-03-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gymtrack_memberprofile_delete_member_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymTrack',
        ),
    ]
