# Generated by Django 4.0.2 on 2022-03-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_gymtrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.CharField(max_length=20)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('neck', models.IntegerField(default=0)),
                ('shoulder', models.IntegerField(default=0)),
                ('chest', models.IntegerField(default=0)),
                ('upperArm', models.IntegerField(default=0)),
                ('forearm', models.IntegerField(default=0)),
                ('upperAbdomen', models.IntegerField(default=0)),
                ('lowerAbdomen', models.IntegerField(default=0)),
                ('waist', models.IntegerField(default=0)),
                ('hips', models.IntegerField(default=0)),
                ('thighs', models.IntegerField(default=0)),
                ('calf', models.IntegerField(default=1)),
                ('g_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guid', to='core.authuser')),
            ],
        ),
    ]
