# Generated by Django 4.0.3 on 2022-04-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gymtrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='isAdminVerified',
            field=models.BooleanField(default=False),
        ),
    ]
