# Generated by Django 4.0.3 on 2022-04-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_authuser_isadminverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordDate', models.CharField(max_length=20)),
                ('a_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auid', to='core.authuser')),
            ],
        ),
    ]
