# Generated by Django 4.0.3 on 2022-04-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='profileName',
            field=models.CharField(default='no name', max_length=40),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='name',
            field=models.CharField(default='no value', max_length=40),
        ),
    ]
